#AULA 01 - COMENTÁRIOS

#PARA COMENTÁRIOS DE UMA LINHA UTILIZAMOS O HASHTAG #

"""
PARA COMENTÁRIOS EM VÁRIAS LINHAS, COMENTÁRIOS LONGOS COLOCAMOS ENTRE 3 ASPAS
PARA COMENTÁRIOS EM VÁRIAS LINHAS, COMENTÁRIOS LONGOS COLOCAMOS ENTRE 3 ASPAS 
PARA COMENTÁRIOS EM VÁRIAS LINHAS, COMENTÁRIOS LONGOS COLOCAMOS ENTRE 3 ASPAS 

"""

